import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ptang' at '8/6/15 1:21 PM' with Gradle 2.5
 *
 * @author ptang, @date 8/6/15 1:21 PM
 */
public class TicTacToe {
    private final String BOARD_ROW = " %s | %s | %s\n";
    private final String BOARD_LINE = "-----------\n";
    private final int MAX_BOARD_ROWS = 5;
    private final int SPOTS_IN_ROW = 3;

    private PrintStream printStream;
    private List<String> moveGrid;
    private Player player1;

    public TicTacToe(PrintStream printStream) {

        this.printStream = printStream;
    }

    public void start() {
        moveGrid = new ArrayList<>();
        setUpMoveGrid(moveGrid);
        BufferedReader inputStream = new BufferedReader(new InputStreamReader(System.in));
        player1 = new Player(moveGrid,System.out, inputStream);

        printStream.print(produceBoard(moveGrid));
    }

    public void play() {
        update(moveGrid, player1);
    }

    public void update(List<String> moveGrid, Player player1) {
        player1.prompt();
        player1.move();
        printStream.print(produceBoard(moveGrid));
    }

    private void setUpMoveGrid(List<String> moveGrid) {
        for (int i = 0; i < 9; i++) {
            moveGrid.add(new String(" "));
        }
    }

    private String produceBoard(List<String> moveGrid) {
        String board = "";
        for (int i = 0; i < MAX_BOARD_ROWS; i++) {
            if (i % 2 == 0) {
                board += produceRow(moveGrid,i);
            } else {
                board += BOARD_LINE;
            }
        }

        return board;
    }

    private String produceRow(List<String> moveGrid, int rowNumber) {
        rowNumber /= 2;
        return String.format(BOARD_ROW,
                moveGrid.get(rowNumber*SPOTS_IN_ROW),
                moveGrid.get(rowNumber*SPOTS_IN_ROW + 1),
                moveGrid.get(rowNumber*SPOTS_IN_ROW + 2));
    }
}
