import org.junit.Before;
import org.junit.Test;

import java.io.BufferedReader;
import java.io.PrintStream;
import java.util.ArrayList;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ptang' at '8/6/15 1:21 PM' with Gradle 2.5
 *
 * @author ptang, @date 8/6/15 1:21 PM
 */
public class TicTacToeTest {

    private PrintStream printStream;
    private TicTacToe ticTacToe;
    private ArrayList<String> moveGrid;
    private BufferedReader inputStream;
    private Player player1;
    private Player player2;

    @Before
    public void setUp() throws Exception {
        printStream = mock(PrintStream.class);
        ticTacToe = new TicTacToe(printStream);
        inputStream = mock(BufferedReader.class);
    }

    private void setUpMoveGridForTest() {
        moveGrid = new ArrayList<>();
        for (int i = 0; i < 9; i++) {
            moveGrid.add(new String(" "));
        }
    }

    private void setUpPlayer1() {
        player1 = new Player(moveGrid,printStream, inputStream, 1);
    }

    private void setUpPlayer2() {
        player2 = new Player(moveGrid,printStream, inputStream, 2);
    }

    @Test
    public void shouldDrawBoardWhenStart() throws Exception {
        ticTacToe.start();

        verify(printStream).print(  "   |   |  \n" +
                                    "-----------\n" +
                                    "   |   |  \n" +
                                    "-----------\n" +
                                    "   |   |  \n");

    }

    @Test
    public void shouldDrawBoardWithXInSpot5IfPlayer1Inputs5() throws Exception {
        setUpMoveGridForTest();
        setUpPlayer1();
        when(inputStream.readLine()).thenReturn("5");
        ticTacToe.update(moveGrid, player1);

        verify(printStream).print(  "   |   |  \n" +
                                    "-----------\n" +
                                    "   | X |  \n" +
                                    "-----------\n" +
                                    "   |   |  \n");
    }

    @Test
    public void shouldDrawBoardWithXInSpot9IfPlayer1Inputs9() throws Exception {
        setUpMoveGridForTest();
        setUpPlayer1();

        when(inputStream.readLine()).thenReturn("9");
        ticTacToe.update(moveGrid, player1);

        verify(printStream).print(  "   |   |  \n" +
                                    "-----------\n" +
                                    "   |   |  \n" +
                                    "-----------\n" +
                                    "   |   | X\n");
    }

    @Test
    public void shouldDrawBoardWithOInSpot4IfPlayer2Inputs4() throws Exception {
        setUpMoveGridForTest();
        setUpPlayer2();
        when(inputStream.readLine()).thenReturn("4");
        ticTacToe.update(moveGrid, player2);

        verify(printStream).print(  "   |   |  \n" +
                "-----------\n" +
                " O |   |  \n" +
                "-----------\n" +
                "   |   |  \n");
    }


}
